/**
 */
package patternGenerator.decentralizedPattern.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import patternGenerator.decentralizedPattern.util.DecentralizedPatternAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class DecentralizedPatternItemProviderAdapterFactory extends DecentralizedPatternAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DecentralizedPatternItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link patternGenerator.decentralizedPattern.Node} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NodeItemProvider nodeItemProvider;

	/**
	 * This creates an adapter for a {@link patternGenerator.decentralizedPattern.Node}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNodeAdapter() {
		if (nodeItemProvider == null) {
			nodeItemProvider = new NodeItemProvider(this);
		}

		return nodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link patternGenerator.decentralizedPattern.Master} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MasterItemProvider masterItemProvider;

	/**
	 * This creates an adapter for a {@link patternGenerator.decentralizedPattern.Master}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMasterAdapter() {
		if (masterItemProvider == null) {
			masterItemProvider = new MasterItemProvider(this);
		}

		return masterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link patternGenerator.decentralizedPattern.Slave} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SlaveItemProvider slaveItemProvider;

	/**
	 * This creates an adapter for a {@link patternGenerator.decentralizedPattern.Slave}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSlaveAdapter() {
		if (slaveItemProvider == null) {
			slaveItemProvider = new SlaveItemProvider(this);
		}

		return slaveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link patternGenerator.decentralizedPattern.UnderlyingSubsystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnderlyingSubsystemItemProvider underlyingSubsystemItemProvider;

	/**
	 * This creates an adapter for a {@link patternGenerator.decentralizedPattern.UnderlyingSubsystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnderlyingSubsystemAdapter() {
		if (underlyingSubsystemItemProvider == null) {
			underlyingSubsystemItemProvider = new UnderlyingSubsystemItemProvider(this);
		}

		return underlyingSubsystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link patternGenerator.decentralizedPattern.RegionalPlanner} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RegionalPlannerItemProvider regionalPlannerItemProvider;

	/**
	 * This creates an adapter for a {@link patternGenerator.decentralizedPattern.RegionalPlanner}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRegionalPlannerAdapter() {
		if (regionalPlannerItemProvider == null) {
			regionalPlannerItemProvider = new RegionalPlannerItemProvider(this);
		}

		return regionalPlannerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link patternGenerator.decentralizedPattern.Peer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PeerItemProvider peerItemProvider;

	/**
	 * This creates an adapter for a {@link patternGenerator.decentralizedPattern.Peer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPeerAdapter() {
		if (peerItemProvider == null) {
			peerItemProvider = new PeerItemProvider(this);
		}

		return peerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link patternGenerator.decentralizedPattern.HPeer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HPeerItemProvider hPeerItemProvider;

	/**
	 * This creates an adapter for a {@link patternGenerator.decentralizedPattern.HPeer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHPeerAdapter() {
		if (hPeerItemProvider == null) {
			hPeerItemProvider = new HPeerItemProvider(this);
		}

		return hPeerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link patternGenerator.decentralizedPattern.ConcretePattern} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConcretePatternItemProvider concretePatternItemProvider;

	/**
	 * This creates an adapter for a {@link patternGenerator.decentralizedPattern.ConcretePattern}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConcretePatternAdapter() {
		if (concretePatternItemProvider == null) {
			concretePatternItemProvider = new ConcretePatternItemProvider(this);
		}

		return concretePatternItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (nodeItemProvider != null) nodeItemProvider.dispose();
		if (masterItemProvider != null) masterItemProvider.dispose();
		if (slaveItemProvider != null) slaveItemProvider.dispose();
		if (underlyingSubsystemItemProvider != null) underlyingSubsystemItemProvider.dispose();
		if (regionalPlannerItemProvider != null) regionalPlannerItemProvider.dispose();
		if (peerItemProvider != null) peerItemProvider.dispose();
		if (hPeerItemProvider != null) hPeerItemProvider.dispose();
		if (concretePatternItemProvider != null) concretePatternItemProvider.dispose();
	}

}
